variable "env" {}
variable "tags" {}
variable "vpc_id" {}
variable "sg_cidrs" {}
variable "bastion_cidrs" {}
variable "subnets" {}
variable "instance_type" {}
variable "route53_zone_id" {}
variable "kms" {}
variable "project_name" {}